package com.mxd.entity;

import java.util.Date;

public class Register {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.register_code
     *
     * @mbggenerated
     */
    private String registerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.imei
     *
     * @mbggenerated
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.active_time
     *
     * @mbggenerated
     */
    private Date activeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.id
     *
     * @return the value of register.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.id
     *
     * @param id the value for register.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_code
     *
     * @return the value of register.register_code
     *
     * @mbggenerated
     */
    public String getRegisterCode() {
        return registerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_code
     *
     * @param registerCode the value for register.register_code
     *
     * @mbggenerated
     */
    public void setRegisterCode(String registerCode) {
        this.registerCode = registerCode == null ? null : registerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.imei
     *
     * @return the value of register.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.imei
     *
     * @param imei the value for register.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.username
     *
     * @return the value of register.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.username
     *
     * @param username the value for register.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.status
     *
     * @return the value of register.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.status
     *
     * @param status the value for register.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.create_time
     *
     * @return the value of register.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.create_time
     *
     * @param createTime the value for register.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.update_time
     *
     * @return the value of register.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.update_time
     *
     * @param updateTime the value for register.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.active_time
     *
     * @return the value of register.active_time
     *
     * @mbggenerated
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.active_time
     *
     * @param activeTime the value for register.active_time
     *
     * @mbggenerated
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }
}