package com.mxd.entity;

public class Version {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.ver
     *
     * @mbggenerated
     */
    private String ver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.ver_num
     *
     * @mbggenerated
     */
    private Integer verNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.update_type
     *
     * @mbggenerated
     */
    private String updateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.code
     *
     * @return the value of version.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.code
     *
     * @param code the value for version.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.name
     *
     * @return the value of version.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.name
     *
     * @param name the value for version.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.ver
     *
     * @return the value of version.ver
     *
     * @mbggenerated
     */
    public String getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.ver
     *
     * @param ver the value for version.ver
     *
     * @mbggenerated
     */
    public void setVer(String ver) {
        this.ver = ver == null ? null : ver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.ver_num
     *
     * @return the value of version.ver_num
     *
     * @mbggenerated
     */
    public Integer getVerNum() {
        return verNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.ver_num
     *
     * @param verNum the value for version.ver_num
     *
     * @mbggenerated
     */
    public void setVerNum(Integer verNum) {
        this.verNum = verNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.update_type
     *
     * @return the value of version.update_type
     *
     * @mbggenerated
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.update_type
     *
     * @param updateType the value for version.update_type
     *
     * @mbggenerated
     */
    public void setUpdateType(String updateType) {
        this.updateType = updateType == null ? null : updateType.trim();
    }
}